### ISSUE TITLE
“import”ed Eta’s “config” does not configure.

### ISSUE THREAD

**Issue by issuefiler** [eta-dev/eta#113]
# I can’t configure _Eta_ when `import`ing it. What should I do?

### I only `import`ed Eta, but somehow it got `require`’d as well, creating another _**unreachable**_ clone of the `Eta.config` in use.

I clearly `import`ed _Eta_. Never `require`’d.

```javascript
import * as Eta from "eta";
for(const key in Eta.defaultConfig) {
	delete Eta.defaultConfig[key];
}
app.engine("Eta", Eta.renderFile);
app.set("view engine", "Eta");
```

Setting the `Eta.config` did not affect the `E` at all. As if there was another clone of the `Eta.config`.

Tried removing every source file except for `eta.es.js`, which should never be used, and got:

```javascript
Error: Cannot find module 'B:\……\node_modules\eta\dist\eta.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:968:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:961:15)
    at resolveExports (node:internal/modules/cjs/loader:478:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at new View (B:\……\node_modules\express\lib\view.js:81:14)
    at Function.render (B:\……\node_modules\express\lib\application.js:570:12) {
  code: 'MODULE_NOT_FOUND',
  path: 'B:\\……\\node_modules\\eta\\package.json'
}
```

### It turned out _Express_ `require`d it.

https://github.com/expressjs/express/blob/5c4f3e7cc76fed9b42c27cebcdd9d66ef63092f9/lib/view.js#L80-L81

```javascript
// default engine export
var fn = require(mod).__express
```

And in this _**new**_ instance of _Eta_, you have another `Eta.config` that is unaffected, unaltered, and _**in use**_.

**Comment by issuefiler** [comment]
Closing, I was told that I could manually give the `import`ed view engine instance to _Express_.
