### ISSUE TITLE
Eta Error: Loading file: C:\...\views\homepage.eta failed: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by GamerGirlandCo** [eta-dev/eta#149]
**Describe the bug**
none of my templates are rendering. everything fails with this error:

```
Eta Error: Loading file: C:\diamond-head-org\views\homepage.eta failed:

Cannot read property 'replace' of undefined
    at EtaErr (C:\diamond-head-org\node_modules\eta\src\err.ts:26:15)
    at loadFile (C:\diamond-head-org\node_modules\eta\src\file-handlers.ts:53:11)
    at handleCache (C:\diamond-head-org\node_modules\eta\src\file-handlers.ts:81:10)
    at tryHandleCache (C:\diamond-head-org\node_modules\eta\src\file-handlers.ts:99:26)
    at View.renderFile [as engine] (C:\diamond-head-org\node_modules\eta\src\file-handlers.ts:241:10)
    at View.render (C:\diamond-head-org\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\diamond-head-org\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\diamond-head-org\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\diamond-head-org\node_modules\express\lib\response.js:1012:7)
    at C:\diamond-head-org\routes\misc.ts:11:6
    at step (C:\diamond-head-org\routes\misc.ts:33:23)
    at Object.next (C:\diamond-head-org\routes\misc.ts:14:53)
    at C:\diamond-head-org\routes\misc.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\diamond-head-org\routes\misc.ts:4:12)
    at C:\diamond-head-org\routes\misc.ts:10:27
```

**To Reproduce**
1. call `res.render` from express

**Expected behavior**
the template to render.

**Screenshots**
N/A; error is shown above.

**Package & Environment Details**
 - Node
 - Version: 15.0.1

**Additional context**
i've searched everywhere in my `views` directory for any calls to `.replace`, however the only results are client-side js, i.e., not wrapped in `<?` and `?>` (my chosen delimiters)

![image](https://user-images.githubusercontent.com/37163052/139281345-55017788-a32c-407d-aaf2-ec5d7b5efee8.png)

my configuration, in case it's relevant:

```js
eta.configure({
	cache: true,
	tags: ["<?", "?>"],
	varName: "_"
});
```

**Comment by nebrelbug** [comment]
@GamerGirlandCo were you able to resolve the issue?

**Comment by GamerGirlandCo** [comment]
> @GamerGirlandCo were you able to resolve the issue?

yep! turns out that it was because one of the variables i passed to the render function was named "tags", which eta already uses internally.
